### ISSUE TITLE
EN TANT QUE CLIENT JE PEUX FILTRER UNE RECHERCHE DE SERVICE DE MENAGE

### ISSUE THREAD

**Issue by Zobidsaad** [manal-978/projet_agile#18]

**Comment by laakili** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
<title>Interface Client </title>

<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://kit.fontawesome.com/45e38e596f.js" crossorigin="anonymous"></script>
<link rel="stylesheet" href="styletrans.css">
<link rel="stylesheet" href="../Html/assets/css/bootstrap.min.css">

</head>



<header class="w3-container  w3-center;  ">

</header>

<body>


<div style="margin-top : 200px ; margin-left : 50px;">
    <form method="post" action="">
        
        
        <div id="from">
            <label  for="inputEmail4">Type Immeuble </label>
            <input type="text" name="depart" class="form-control " style="width:500px" id="inputEmail4" placeholder="Type Immeuble">
        </div>
        <div id="reply">
            <label style="margin-right: 10px" for="inputPassword4">Surface </label>
            <input type="text" name="arrivee" class="form-control" style="width:500px" id="inputPassword4" placeholder="Surface">
        </div>
         <div id="reply">
            <label style="margin-right: 10px" for="inputPassword4">Nombre de personne</label>
            <input type="text" name="arrivee" class="form-control" style="width:500px" id="inputPassword4" placeholder="Nombre de personne">
        </div>
        
       

        <br>
        <button type="submit" name="commande" class="btn btn-primary">Demander</button>
    </form>
</div>



<div style="margin-top: 5% ;">
    <div style="width: 50%; float:left ;">
        


    
    </div>
    <div style="position:relative;width: 40%;padding-right  : 5px; float:right ;margin-right: 5px ;margin-left: 10px;">
   
    </div>
</div>






</body>


</html>
